### ISSUE TITLE
Bones needs a new name!

### ISSUE THREAD

**Issue by glebec** [glebec/gshopper-demo#1]
@star-lebec — don't you think "Bones" is a little too dry? Nyuk nyuk. Let's have a custom name!

**Comment by star-lebec** [comment]
I'm on mobile right now, but yeah, def!

**Comment by star-lebec** [comment]
Oh, follow-up @glebec I thought that maybe `dogbones` was a good name, what do you think?

**Comment by star-lebec** [comment]
Here's an example:

```js
console.log('hello world')
```
